import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { type ReactNode } from "react";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { getCssText } from "../stitches.config";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
  modal: ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <head>
        <style
          dangerouslySetInnerHTML={{
            __html: getCssText(),
          }}
        />
      </head>
      <body className={inter.className}>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
